spring:
  application:
    name: infinance-calculator-backend
  profiles:
    active: dev
  config:
    import:
      - classpath:application-assumptions.yml

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
