apiVersion: v1
kind: ConfigMap
metadata:
  name: infinance-config
  namespace: infinance
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/infinance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  APP_CORS_ALLOWED_ORIGINS: https://calculator.example.com
