package com.infinance.reports.service;

import com.infinance.common.dto.BaseAssumptionsDto;
import com.infinance.reports.dto.PersonalizedReportRequest;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

@Service
public class ReportExportService {

    public byte[] exportPdf(PersonalizedReportRequest request) {
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, output);
            document.open();
            document.add(new Paragraph(request.reportTitle(), new Font(Font.HELVETICA, 18, Font.BOLD)));
            document.add(new Paragraph("Prepared for: " + request.customerName()));
            document.add(new Paragraph(" "));
            addPdfTable(document, "Calculator results", request.results());
            if (request.assumptions() != null) {
                document.add(new Paragraph(" "));
                addPdfTable(document, "Assumptions", assumptionsAsMap(request.assumptions()));
            }
            document.add(new Paragraph("Generated by InFinance Calculator"));
            document.close();
            return output.toByteArray();
        } catch (Exception exception) {
            throw new IllegalStateException("Unable to generate PDF report", exception);
        }
    }

    public byte[] exportExcel(PersonalizedReportRequest request) {
        try (XSSFWorkbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet("Report");
            int rowIndex = 0;
            Row title = sheet.createRow(rowIndex++);
            title.createCell(0).setCellValue(request.reportTitle());
            Row customer = sheet.createRow(rowIndex++);
            customer.createCell(0).setCellValue("Prepared for");
            customer.createCell(1).setCellValue(request.customerName());
            rowIndex++;
            rowIndex = addExcelSection(sheet, rowIndex, "Calculator results", request.results());
            if (request.assumptions() != null) {
                rowIndex++;
                addExcelSection(sheet, rowIndex, "Assumptions", assumptionsAsMap(request.assumptions()));
            }
            sheet.autoSizeColumn(0);
            sheet.autoSizeColumn(1);
            workbook.write(output);
            return output.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to generate Excel report", exception);
        }
    }

    private void addPdfTable(Document document, String heading, Map<String, Object> values) throws Exception {
        document.add(new Paragraph(heading, new Font(Font.HELVETICA, 13, Font.BOLD)));
        PdfPTable table = new PdfPTable(2);
        table.setWidths(new float[]{1.5f, 3f});
        table.addCell(new Phrase("Metric"));
        table.addCell(new Phrase("Value"));
        flatten(values).forEach((key, value) -> {
            table.addCell(new Phrase(key));
            table.addCell(new Phrase(String.valueOf(value)));
        });
        document.add(table);
    }

    private int addExcelSection(Sheet sheet, int rowIndex, String heading, Map<String, Object> values) {
        Row section = sheet.createRow(rowIndex++);
        section.createCell(0).setCellValue(heading);
        for (Map.Entry<String, Object> entry : flatten(values).entrySet()) {
            Row row = sheet.createRow(rowIndex++);
            row.createCell(0).setCellValue(entry.getKey());
            Cell value = row.createCell(1);
            Object raw = entry.getValue();
            if (raw instanceof Number number) {
                value.setCellValue(number.doubleValue());
            } else {
                value.setCellValue(String.valueOf(raw));
            }
        }
        return rowIndex;
    }

    private Map<String, Object> assumptionsAsMap(BaseAssumptionsDto assumptions) {
        java.util.LinkedHashMap<String, Object> values = new java.util.LinkedHashMap<>();
        values.put("Financial year", assumptions.financialYear());
        values.put("Inflation rate", assumptions.inflationRate());
        values.put("Expected equity return", assumptions.expectedEquityReturn());
        values.put("Expected debt return", assumptions.expectedDebtReturn());
        values.put("Statutory disclaimer", assumptions.statutoryDisclaimer());
        values.put("Module-specific assumptions", assumptions.moduleSpecificAssumptions());
        return values;
    }

    private Map<String, Object> flatten(Map<String, Object> source) {
        java.util.LinkedHashMap<String, Object> flattened = new java.util.LinkedHashMap<>();
        source.forEach((key, value) -> flattenValue(flattened, key, value));
        return flattened;
    }

    private void flattenValue(Map<String, Object> target, String prefix, Object value) {
        if (value instanceof Map<?, ?> nested) {
            nested.forEach((key, nestedValue) -> flattenValue(target, prefix + "." + key, nestedValue));
        } else if (value instanceof List<?> list) {
            target.put(prefix, String.join(", ", list.stream().map(String::valueOf).toList()));
        } else {
            target.put(prefix, value == null ? "" : value);
        }
    }
}
